### ISSUE TITLE
WebExtensions fork

### ISSUE THREAD

**Issue by Keith94** [justindarc/firesize#3]
A WebExtensions version was published on AMO: https://addons.mozilla.org/firefox/addon/window-resize/ which supports Firefox 57 and later. I guess the original add-on is just abandoned now.

**Comment by DJCrashdummy** [comment]
@Keith94 is there anywhere the source, since there is no repo at github and at AMO i found no link or something...

btw: at least an english description at https://addons.mozilla.org/firefox/addon/window-resize/ would make sense!

**Comment by Keith94** [comment]
No, I didn't find any source link. This seems to be the author: https://github.com/leave00608

**Comment by DJCrashdummy** [comment]
maybe @leave00608 can leave a statement if the assumption is correct?
